MusicStore/ViewModels/ShoppingCartViewModel.cs
using MusicStore.Models;
using MusicStore.Models.Database.Movie;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MusicStore.ViewModels
{
    public class ShoppingCartViewModel
    {
        public List<MovieCart> CartItems { get; set; }
        public decimal CartTotal { get; set; }
    }
}

MusicStore/Controllers/CheckoutController.cs
using MusicStore.EntityContext;
using MusicStore.Models;
using MusicStore.Models.Database.Movie;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicStore.Controllers
{
    public class CheckoutController : Controller
    {
        readonly MovieStoreEntities storeDB = new MovieStoreEntities();
        //
        // GET: /Checkout/
        public ActionResult AddressAndPayment()
        {
            return View();
        }
        //
        // POST: /Checkout/AddressAndPayment
        /// <summary>
        /// Submit order-re kattintva lefut
        /// </summary>
        /// <param name="values"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AddressAndPayment(FormCollection values)
        {
            var order = new MovieOrder();
            TryUpdateModel(order);
            try
            {
                order.Username = User.Identity.Name;
                order.OrderDate = DateTime.Now;
                //Process the order
                var cart = ShoppingCart.GetCart(HttpContext);
                cart.CreateOrder(order);
                return RedirectToAction("Complete", new { errortype = order.MovieOrderId });
            }
            catch
            {
                //Invalid - redisplay with errors
                return View(order);
            }
        }
        //
        // GET: /Checkout/Complete
        public ActionResult Complete(int id)
        {
            // Validate customer owns this order
            bool isValid = this.storeDB.MovieOrders.Any(
            o => o.MovieOrderId == id &&
            o.Username == User.Identity.Name);
            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }
	}
}

MusicStore/Controllers/ShoppingCartController.cs
using MusicStore.EntityContext;
using MusicStore.Models;
using MusicStore.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        readonly MovieStoreEntities storeDB = new MovieStoreEntities();
        //
        // GET: /ShoppingCart/
        /// <summary>
        /// visszaadja username alapján a chart-ot
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        /// <summary>
        ///AlbumId alapján
        ///a username-hez tartozo chart-hoz
        ///hozzáadja az albumot
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedAlbum = storeDB.Movies
            .Single(movie => movie.MovieId == id);
            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.AddToCart(addedAlbum);
            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5

        /// <summary>
        /// Albumid alapjan eltávolítja az Albumot
        /// A username-hez tartozp Chart-ból
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);
            // Get the name of the album to display confirmation
            string movieName = storeDB.MovieCarts
            .Single(item => item.MovieRecordId == id).Movie.MovieTitle;
            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);
            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel()
            {
                Message = Server.HtmlEncode(movieName) +
                "has been removed from your shopping cart.",
                CartTotal=cart.GetTotal(),
                CartCount=cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        //返回的一个子视图
        /// <summary>
        /// Visszaadja, hogy hány elem van a cart-ban
        /// <returns></returns>
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            ViewData["CartCount"] = cart.GetCount();
            return PartialView(cart);
        }
	}
}

MusicStore/Controllers/StoreController.cs
using MusicStore.EntityContext;
using MusicStore.Models;
using MusicStore.Models.Database.Movie;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MusicStore.Controllers
{
    public class StoreController : Controller
    {
        private readonly MovieStoreEntities storeDB = new MovieStoreEntities();
        //
        // GET: /Store/

            /// <summary>
        /// Kilistázza a műfajokat
        /// </summary>
        /// <returns></returns>

        public ActionResult Index()
        {
            var genres = this.storeDB.MovieGenres.ToList();
            return View(genres);
        }
        //
        // GET: /Store/Browse

        /// <summary>
        ///A az albumokat amiknek a genre-jük genre továbbadja a view-nak
        /// </summary>
        /// <param name="genre"></param>
        /// <returns></returns>
        public ActionResult Browse(string genre)
        {
            // Retrieve Genre and its Associated Albums from database
            //Include("Albums")指定返回结果要包含关联Album
            MovieGenre example = this.storeDB.MovieGenres.Include("Movies").Single(p => p.MovieGenreName == genre);
            return View(example);
        }
        //
        // GET: /Store/Details

        /// <summary>
        // Az AlbumId alapján lekéri az albumot és azt az albumot adja tovább a View-nak
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = this.storeDB.Movies.Find(id);
            return View(movie);
        }
        //
        // GET: /Store/GenreMenu

        /// <summary>
        /// Oldal sáv a genreknek
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]

        public ActionResult GenreMenu()
        {
            var genres = this.storeDB.MovieGenres.ToList();
            return PartialView(genres);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.storeDB.Dispose();
            }
            base.Dispose(disposing);
        }
	}
}

MusicStore/Views/ShoppingCart/CartSummary.cshtml
@Html.ActionLink("Cart (" + ViewData["CartCount"] + ")", "Index", "ShoppingCart",
new { id = "cart-status" })

MusicStore/Views/ShoppingCart/Index.cshtml
@model MusicStore.ViewModels.ShoppingCartViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".RemoveLink").click(function () {
            var recordDelete = $(this).attr("data-id");
            if (recordDelete != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/RemoveFromCart"
                      , { id: recordDelete }
                      , function (data) {
                          // Successful requests get here
                          // Update the page elements
                          if (data.ItemCount == 0) {
                              $('#row-' + data.DeleteId).fadeOut('slow');
                          }
                          else {
                              $('#item-count-' + data.DeleteId).text(data.ItemCount);
                          }
                          $('#cart-total').text(data.CartTotal);
                          $('#update-message').text(data.Message);
                          $('#cart-status').text('Cart (' + data.CartCount + ')');
                      });
            }
        });
    });
    function handleUpdate() {
        // Load and deserialize the returned JSON data
        var json = context.get_data();
        var data = Sys.Serialization.JavaScriptSerializer.deserialize(json);
        // Update the page elements
        if (data.ItemCount == 0) {
            $('#row-' + data.DeleteId).fadeOut('slow');
        } else {
            $('#item-count-' + data.DeleteId).text(data.ItemCount);
        }
        $('#cart-total').text(data.CartTotal);
        $('#update-message').text(data.Message);
        $('#cart-status').text('Cart (' + data.CartCount + ')');
    }
</script>
<h3>
    <em>Review</em>
     Your carts:
</h3>

<p class="button">
    @Html.ActionLink("Check out>>","AddressAndPayment","Checkout")
</p>
<div id="update-message">
</div>
<table>
    <tr>
        <th>
            Album Name
        </th>
        <th>
            Price (each)
        </th>
        <th>
            Quantity
        </th>
        <th>

        </th>
    </tr>
    @foreach(var item in Model.CartItems)
    {
        <tr id="row-@item.MovieRecordId">
            <td>
                @Html.ActionLink(item.Movie.MovieTitle, "Details", "Store", new { id=item.MovieId},null)
            </td>
            <td>
                @item.Movie.MoviePrice
            </td>
            <td id="item-count-@item.MovieRecordId">
                @item.Count
            </td>
            <td>
                <a href="#" class="RemoveLink" data-id="@item.MovieRecordId">
                    remove from cart
                </a>
            </td>
        </tr>
    }
    <tr>
        <td>
            Total
        </td>
        <td id="cart-total">
            @Model.CartTotal
        </td>
    </tr>
</table>